export type Language = 'en' | 'tr' | 'es' | 'fr' | 'ar' | 'hi' | 'bn' | 'ru' | 'pt' | 'id';

export const languages: { name: string; code: Language }[] = [
    { name: "English", code: "en" },
    { name: "Türkçe", code: "tr" },
    { name: "Español", code: "es" },
    { name: "Français", code: "fr" },
    { name: "العربية", code: "ar" },
    { name: "हिन्दी", code: "hi" },
    { name: "বাংলা", code: "bn" },
    { name: "Русский", code: "ru" },
    { name: "Português", code: "pt" },
    { name: "Bahasa Indonesia", code: "id" },
];

const en = {
    home: 'Home',
    explore: 'Explore',
    notifications: 'Notifications',
    profile: 'Profile',
    createPost: 'Create Post',
    settings: 'Settings',
    appearance: 'Appearance',
    toggleTheme: 'Toggle theme',
    colorTheme: 'Color Theme',
    language: 'Language',
    logout: 'Logout',
    whatsOnYourMind: "What's on your mind?",
    shareWithCommunity: "Share your thoughts, photos, videos, or links with the community.",
    writePostPlaceholder: "What's happening? #hashtag",
    selectImageToUpload: 'Select an image to upload',
    selectVideoToUpload: 'Select a video to upload',
    post: 'Post',
    posting: 'Posting...',
    linkUrlPlaceholder: 'Enter link to share',
    save: 'Save',
    saved: 'Saved',
    reportPost: 'Report Post',
    reportDescription: 'Please provide a reason for reporting this post. Your feedback is important for community safety.',
    reportPlaceholder: 'e.g., spam, inappropriate content, harassment...',
    cancel: 'Cancel',
    submitReport: 'Submit Report',
    deletePost: 'Delete Post',
    createNewPost: 'Create a new post',
    welcomeToUmmahConnect: 'Welcome to BANG!',
    writeAComment: 'Write a comment...',
    send: 'Send',
    // Explore Page
    exploreDescription: 'Discover the most popular content from the community.',
    mostLikedPosts: 'Most Liked Posts',
    mostCommentedPosts: 'Most Commented Posts',
    noImagePostsToExplore: 'No image posts to explore yet.',
    // Notifications Page
    noNewNotifications: 'You have no new notifications.',
    // Profile Page
    following: 'Following',
    followers: 'Followers',
    follow: 'Follow',
    message: 'Message',
    posts: 'Posts',
    replies: 'Replies',
    likes: 'Likes',
    noPostsYet: 'No posts yet.',
    noRepliesYet: 'No replies yet.',
    noLikesYet: 'No likes yet.',
    savedPostsArePrivate: 'Saved posts are private.',
    youHaventSavedPosts: "You haven't saved any posts yet.",
    youHaventRepliedYet: "You haven't replied to any posts yet.",
    youHaventLikedYet: "You haven't liked any posts yet.",
    // Toasts & Alerts
    error: 'Error',
    success: 'Success',
    couldNotFetchDashboardStats: 'Could not fetch dashboard stats.',
    userDeleted: 'User Deleted',
    userDeletedDesc: (name: string) => `${name} has been successfully deleted.`,
    couldNotDeleteUser: 'Could not delete user. Check Firestore rules.',
    postUpdated: 'Post Updated',
    postUpdatedDesc: (status: 'banned' | 'active') => `Post has been ${status === 'banned' ? 'banned' : 'unbanned'}.`,
    couldNotUpdatePost: 'Could not update post status.',
    postDeleted: 'Post Deleted',
    postDeletedDesc: 'The post has been successfully deleted.',
    couldNotDeletePost: 'Could not delete post. Check Firestore rules.',
    couldNotFetchPosts: 'Could not fetch posts. You may need to create Firestore indexes.',
    unfollowed: 'Unfollowed',
    unfollowedDesc: (name: string) => `You are no longer following ${name}.`,
    followed: 'Followed',
    followedDesc: (name: string) => `You are now following ${name}.`,
    actionCouldNotBeCompleted: 'Could not complete the action.',
    fileTooLarge: 'File Too Large',
    imageTooLargeDesc: 'Image must be smaller than 5MB.',
    newAvatarSaved: 'Your new avatar has been saved.',
    newCoverSaved: 'Your new cover photo has been saved.',
    uploadFailed: 'Upload Failed',
    couldNotUploadImage: 'Could not upload your image.',
    couldNotFetchProfile: 'Could not fetch profile user.',
    couldNotFetchUserPosts: 'Could not fetch user posts. You may need to create an index in Firestore.',
    couldNotFetchSavedPosts: 'Could not fetch saved posts.',
    loggedIn: 'Logged in successfully! Redirecting...',
    loginFailed: 'Login Failed',
    googleLoginFailed: 'Could not initiate Google login. Please try again.',
    accountCreated: 'Account created successfully!',
    signupFailed: 'Signup Failed',
    passwordLengthError: 'Password should be at least 6 characters.',
    googleSignupFailed: 'Could not initiate Google signup. Please try again.',
    notAuthenticated: 'Not Authenticated',
    mustBeLoggedIn: 'You must be logged in to create a post.',
    postError: 'Post Error',
    couldNotCreatePost: 'Could not create the post.',
    invalidFile: 'Invalid File',
    invalidImageFile: 'Please select an image file (jpg, png, gif, webp).',
    invalidVideoFile: 'Please select a video file (mp4, webm, ogg).',
    fileTooLarge20MB: 'File must be smaller than 20MB.',
    postPublished: 'Your post has been published.',
    uploadError: 'Upload Error',
    loggedOut: 'Logged Out',
    loggedOutDesc: 'You have been successfully logged out.',
    logoutError: 'Failed to log out.',
    postReported: 'Post Reported',
    reportThanks: 'Thank you for your feedback. We will review this post.',
    couldNotSubmitReport: 'Could not submit your report.',
    mustBeLoggedInToComment: 'You must be logged in to comment.',
    couldNotAddComment: 'Could not add comment.',
    authError: 'Authentication Error',
    mustBeLoggedInToLike: 'You must be logged in to like a post.',
    couldNotUpdateLike: 'Could not update like.',
    mustBeLoggedInToSave: 'You must be logged in to save a post.',
    postUnsaved: 'Post Unsaved',
    postUnsavedDesc: 'Removed from your saved posts.',
    postSaved: 'Post Saved',
    postSavedDesc: 'Added to your saved posts.',
    couldNotSavePost: 'Could not save post.',
    unauthorized: 'Unauthorized',
    unauthorizedDelete: 'You can only delete your own posts.',
    // Facebook Video Warnings
    unsupportedFacebookLink: 'Unsupported Facebook Link',
    unsupportedFacebookLinkDesc: 'This link format is not supported. Please copy the direct video link from the video\'s main page.',
    correctLinkFormats: 'Correct link formats:',
    videoPageInstructions: 'Go to the video page and copy the direct video URL.',
    // Admin Panel
    adminDashboard: 'Admin Dashboard',
    adminWelcome: 'Welcome to the admin control center.',
    totalUsers: 'Total Users',
    totalPosts: 'Total Posts',
    reportedPosts: 'Reported Posts',
    bannedPosts: 'Banned Posts',
    storageUsage: 'Storage Usage',
    storageUsageDesc: 'Monthly cloud storage usage.',
    storageUsageDetail: (usedGb: string, percentage: string, limitGb: number) => `Monthly usage is ${usedGb} GB (${percentage}%) of ${limitGb} GB limit.`,
    usedStorage: 'Used',
    remainingStorage: 'Remaining',
    quickActions: 'Quick Actions',
    quickActionsDesc: 'Perform common administrative tasks.',
    sendGlobalNotification: 'Send Global Notification',
    recalculateStats: 'Recalculate All Stats',
    disableSite: 'Temporarily Disable Site',
    postManagement: 'Post Management',
    postManagementDesc: 'View and manage all user posts. You can ban, unban, or delete posts.',
    author: 'Author',
    content: 'Content',
    reports: 'Reports',
    status: 'Status',
    created: 'Created',
    actions: 'Actions',
    unknownUser: 'Unknown User',
    mediaPost: 'Media Post',
    banPost: 'Ban Post',
    unbanPost: 'Unban Post',
    userManagement: 'User Management',
    userManagementDesc: 'View and manage all registered users.',
    user: 'User',
    email: 'Email',
    joined: 'Joined',
    deleteUser: 'Delete User',
};

const tr: typeof en = {
    home: 'Anasayfa',
    explore: 'Keşfet',
    notifications: 'Bildirimler',
    profile: 'Profil',
    createPost: 'Gönderi Oluştur',
    settings: 'Ayarlar',
    appearance: 'Görünüm',
    toggleTheme: 'Temayı değiştir',
    colorTheme: 'Renk Teması',
    language: 'Dil',
    logout: 'Çıkış Yap',
    whatsOnYourMind: 'Aklında ne var?',
    shareWithCommunity: "Düşüncelerinizi, fotoğraflarınızı, videolarınızı veya bağlantılarınızı toplulukla paylaşın.",
    writePostPlaceholder: "Neler oluyor? #etiket",
    selectImageToUpload: 'Yüklenecek bir resim seçin',
    selectVideoToUpload: 'Yüklenecek bir video seçin',
    post: 'Gönder',
    posting: 'Gönderiliyor...',
    linkUrlPlaceholder: 'Paylaşılacak bağlantıyı girin',
    save: 'Kaydet',
    saved: 'Kaydedildi',
    reportPost: 'Gönderiyi Bildir',
    reportDescription: 'Lütfen bu gönderiyi bildirmek için bir neden belirtin. Geri bildiriminiz topluluk güvenliği için önemlidir.',
    reportPlaceholder: 'örn. spam, uygunsuz içerik, taciz...',
    cancel: 'İptal',
    submitReport: 'Raporu Gönder',
    deletePost: 'Gönderiyi Sil',
    createNewPost: 'Yeni bir gönderi oluştur',
    welcomeToUmmahConnect: 'UmmahConnect\'e Hoş Geldiniz!',
    writeAComment: 'Bir yorum yazın...',
    send: 'Gönder',
    // Explore Page
    exploreDescription: 'Topluluğun en popüler içeriklerini keşfedin.',
    mostLikedPosts: 'En Çok Beğenilen Gönderiler',
    mostCommentedPosts: 'En Çok Yorum Alan Gönderiler',
    noImagePostsToExplore: 'Keşfedilecek resimli gönderi henüz yok.',
    // Notifications Page
    noNewNotifications: 'Yeni bildiriminiz yok.',
    // Profile Page
    following: 'Takip Edilen',
    followers: 'Takipçi',
    follow: 'Takip Et',
    message: 'Mesaj',
    posts: 'Gönderiler',
    replies: 'Yanıtlar',
    likes: 'Beğeniler',
    noPostsYet: 'Henüz gönderi yok.',
    noRepliesYet: 'Henüz yanıt yok.',
    noLikesYet: 'Henüz beğeni yok.',
    savedPostsArePrivate: 'Kaydedilen gönderiler gizlidir.',
    youHaventSavedPosts: 'Henüz hiçbir gönderi kaydetmediniz.',
    youHaventRepliedYet: "Henüz hiçbir gönderiye yanıt vermediniz.",
    youHaventLikedYet: "Henüz hiçbir gönderi beğenmediniz.",
    // Toasts & Alerts
    error: 'Hata',
    success: 'Başarılı',
    couldNotFetchDashboardStats: 'Pano istatistikleri alınamadı.',
    userDeleted: 'Kullanıcı Silindi',
    userDeletedDesc: (name: string) => `${name} başarıyla silindi.`,
    couldNotDeleteUser: 'Kullanıcı silinemedi. Firestore kurallarını kontrol edin.',
    postUpdated: 'Gönderi Güncellendi',
    postUpdatedDesc: (status: 'banned' | 'active') => `Gönderi ${status === 'banned' ? 'yasaklandı' : 'yasağı kaldırıldı'}.`,
    couldNotUpdatePost: 'Gönderi durumu güncellenemedi.',
    postDeleted: 'Gönderi Silindi',
    postDeletedDesc: 'Gönderi başarıyla silindi.',
    couldNotDeletePost: 'Gönderi silinemedi. Firestore kurallarını kontrol edin.',
    couldNotFetchPosts: 'Gönderiler alınamadı. Firestore indeksleri oluşturmanız gerekebilir.',
    unfollowed: 'Takipten Çıkıldı',
    unfollowedDesc: (name: string) => `Artık ${name} kişisini takip etmiyorsunuz.`,
    followed: 'Takip Edildi',
    followedDesc: (name: string) => `Artık ${name} kişisini takip ediyorsunuz.`,
    actionCouldNotBeCompleted: 'İşlem tamamlanamadı.',
    fileTooLarge: 'Dosya Çok Büyük',
    imageTooLargeDesc: 'Resim 5MB\'tan küçük olmalıdır.',
    newAvatarSaved: 'Yeni avatarınız kaydedildi.',
    newCoverSaved: 'Yeni kapak fotoğrafınız kaydedildi.',
    uploadFailed: 'Yükleme Başarısız',
    couldNotUploadImage: 'Resminiz yüklenemedi.',
    couldNotFetchProfile: 'Profil kullanıcısı alınamadı.',
    couldNotFetchUserPosts: 'Kullanıcı gönderileri alınamadı. Firestore\'da bir indeks oluşturmanız gerekebilir.',
    couldNotFetchSavedPosts: 'Kaydedilen gönderiler alınamadı.',
    loggedIn: 'Başarıyla giriş yapıldı! Yönlendiriliyor...',
    loginFailed: 'Giriş Başarısız',
    googleLoginFailed: 'Google ile giriş başlatılamadı. Lütfen tekrar deneyin.',
    accountCreated: 'Hesap başarıyla oluşturuldu!',
    signupFailed: 'Kayıt Başarısız',
    passwordLengthError: 'Şifre en az 6 karakter olmalıdır.',
    googleSignupFailed: 'Google ile kayıt başlatılamadı. Lütfen tekrar deneyin.',
    notAuthenticated: 'Kimlik Doğrulanmadı',
    mustBeLoggedIn: 'Gönderi oluşturmak için giriş yapmalısınız.',
    postError: 'Gönderi Hatası',
    couldNotCreatePost: 'Gönderi oluşturulamadı.',
    invalidFile: 'Geçersiz Dosya',
    invalidImageFile: 'Lütfen bir resim dosyası seçin (jpg, png, gif, webp).',
    invalidVideoFile: 'Lütfen bir video dosyası seçin (mp4, webm, ogg).',
    fileTooLarge20MB: 'Dosya 20MB\'tan küçük olmalıdır.',
    postPublished: 'Gönderiniz yayınlandı.',
    uploadError: 'Yükleme Hatası',
    loggedOut: 'Çıkış Yapıldı',
    loggedOutDesc: 'Başarıyla çıkış yaptınız.',
    logoutError: 'Çıkış yapılamadı.',
    postReported: 'Gönderi Bildirildi',
    reportThanks: 'Geri bildiriminiz için teşekkür ederiz. Bu gönderiyi inceleyeceğiz.',
    couldNotSubmitReport: 'Raporunuz gönderilemedi.',
    mustBeLoggedInToComment: 'Yorum yapmak için giriş yapmalısınız.',
    couldNotAddComment: 'Yorum eklenemedi.',
    authError: 'Kimlik Doğrulama Hatası',
    mustBeLoggedInToLike: 'Bir gönderiyi beğenmek için giriş yapmalısınız.',
    couldNotUpdateLike: 'Beğeni güncellenemedi.',
    mustBeLoggedInToSave: 'Bir gönderiyi kaydetmek için giriş yapmalısınız.',
    postUnsaved: 'Gönderi Kaydedilmedi',
    postUnsavedDesc: 'Kaydedilen gönderilerinizden kaldırıldı.',
    postSaved: 'Gönderi Kaydedildi',
    postSavedDesc: 'Kaydedilen gönderilerinize eklendi.',
    couldNotSavePost: 'Gönderi kaydedilemedi.',
    unauthorized: 'Yetkisiz',
    unauthorizedDelete: 'Yalnızca kendi gönderilerinizi silebilirsiniz.',
    // Facebook Video Warnings
    unsupportedFacebookLink: 'Desteklenmeyen Facebook Bağlantısı',
    unsupportedFacebookLinkDesc: 'Bu bağlantı formatı desteklenmemektedir. Lütfen videonun ana sayfasından doğrudan video bağlantısını kopyalayın.',
    correctLinkFormats: 'Doğru bağlantı formatları:',
    videoPageInstructions: 'Video sayfasına gidin ve doğrudan video URL\'ini kopyalayın.',
    // Admin Panel
    adminDashboard: 'Yönetici Paneli',
    adminWelcome: 'Yönetici kontrol merkezine hoş geldiniz.',
    totalUsers: 'Toplam Kullanıcı',
    totalPosts: 'Toplam Gönderi',
    reportedPosts: 'Raporlanan Gönderiler',
    bannedPosts: 'Yasaklı Gönderiler',
    storageUsage: 'Depolama Kullanımı',
    storageUsageDesc: 'Aylık bulut depolama kullanımı.',
    storageUsageDetail: (usedGb: string, percentage: string, limitGb: number) => `Aylık kullanım ${limitGb} GB limitin ${usedGb} GB'ı (%${percentage}).`,
    usedStorage: 'Kullanılan',
    remainingStorage: 'Kalan',
    quickActions: 'Hızlı İşlemler',
    quickActionsDesc: 'Sık kullanılan yönetimsel görevleri gerçekleştirin.',
    sendGlobalNotification: 'Genel Bildirim Gönder',
    recalculateStats: 'Tüm İstatistikleri Yeniden Hesapla',
    disableSite: 'Siteyi Devre Dışı Bırak',
    message: 'Mesaj',
    postManagement: 'Gönderi Yönetimi',
    postManagementDesc: 'Tüm kullanıcı gönderilerini görüntüleyin ve yönetin. Gönderileri yasaklayabilir, yasağını kaldırabilir veya silebilirsiniz.',
    author: 'Yazar',
    content: 'İçerik',
    reports: 'Raporlar',
    status: 'Durum',
    created: 'Oluşturulma',
    actions: 'İşlemler',
    unknownUser: 'Bilinmeyen Kullanıcı',
    mediaPost: 'Medya Gönderisi',
    banPost: 'Gönderiyi Yasakla',
    unbanPost: 'Yasağı Kaldır',
    userManagement: 'Kullanıcı Yönetimi',
    userManagementDesc: 'Tüm kayıtlı kullanıcıları görüntüleyin ve yönetin.',
    user: 'Kullanıcı',
    email: 'E-posta',
    joined: 'Katılım Tarihi',
    deleteUser: 'Kullanıcıyı Sil',
};

const es: typeof en = {
    home: 'Inicio',
    explore: 'Explorar',
    notifications: 'Notificaciones',
    profile: 'Perfil',
    createPost: 'Crear Publicación',
    settings: 'Ajustes',
    appearance: 'Apariencia',
    toggleTheme: 'Cambiar tema',
    colorTheme: 'Tema de color',
    language: 'Idioma',
    logout: 'Cerrar Sesión',
    whatsOnYourMind: '¿Qué estás pensando?',
    shareWithCommunity: "Comparte tus pensamientos, fotos, videos o enlaces con la comunidad.",
    writePostPlaceholder: "¿Qué está pasando? #hashtag",
    selectImageToUpload: 'Selecciona una imagen para subir',
    selectVideoToUpload: 'Selecciona un video para subir',
    post: 'Publicar',
    posting: 'Publicando...',
    linkUrlPlaceholder: 'Ingresa el enlace para compartir',
    save: 'Guardar',
    saved: 'Guardado',
    reportPost: 'Reportar Publicación',
    reportDescription: 'Por favor, proporciona una razón para reportar esta publicación. Tus comentarios son importantes para la seguridad de la comunidad.',
    reportPlaceholder: 'ej. spam, contenido inapropiado, acoso...',
    cancel: 'Cancelar',
    submitReport: 'Enviar Reporte',
    deletePost: 'Eliminar Publicación',
    createNewPost: 'Crear una nueva publicación',
    welcomeToUmmahConnect: '¡Bienvenido a UmmahConnect!',
    writeAComment: 'Escribe un comentario...',
    send: 'Enviar',
    // Explore Page
    exploreDescription: 'Descubre el contenido más popular de la comunidad.',
    mostLikedPosts: 'Publicaciones con Más Me Gusta',
    mostCommentedPosts: 'Publicaciones Más Comentadas',
    noImagePostsToExplore: 'Aún no hay publicaciones con imágenes para explorar.',
    // Notifications Page
    noNewNotifications: 'No tienes notificaciones nuevas.',
    // Profile Page
    following: 'Siguiendo',
    followers: 'Seguidores',
    follow: 'Seguir',
    message: 'Mensaje',
    posts: 'Publicaciones',
    replies: 'Respuestas',
    likes: 'Me Gusta',
    noPostsYet: 'Aún no hay publicaciones.',
    noRepliesYet: 'Aún no hay respuestas.',
    noLikesYet: 'Aún no hay "me gusta".',
    savedPostsArePrivate: 'Las publicaciones guardadas son privadas.',
    youHaventSavedPosts: 'Aún no has guardado ninguna publicación.',
    youHaventRepliedYet: "Aún no has respondido a ninguna publicación.",
    youHaventLikedYet: "Aún no te ha gustado ninguna publicación.",
    // Toasts & Alerts
    error: 'Error',
    success: 'Éxito',
    couldNotFetchDashboardStats: 'No se pudieron obtener las estadísticas del panel.',
    userDeleted: 'Usuario Eliminado',
    userDeletedDesc: (name: string) => `${name} ha sido eliminado correctamente.`,
    couldNotDeleteUser: 'No se pudo eliminar el usuario. Comprueba las reglas de Firestore.',
    postUpdated: 'Publicación Actualizada',
    postUpdatedDesc: (status: 'banned' | 'active') => `La publicación ha sido ${status === 'banned' ? 'prohibida' : 'desprohibida'}.`,
    couldNotUpdatePost: 'No se pudo actualizar el estado de la publicación.',
    postDeleted: 'Publicación Eliminada',
    postDeletedDesc: 'La publicación ha sido eliminada correctamente.',
    couldNotDeletePost: 'No se pudo eliminar la publicación. Comprueba las reglas de Firestore.',
    couldNotFetchPosts: 'No se pudieron obtener las publicaciones. Es posible que necesites crear índices de Firestore.',
    unfollowed: 'Dejado de Seguir',
    unfollowedDesc: (name: string) => `Ya no sigues a ${name}.`,
    followed: 'Seguido',
    followedDesc: (name: string) => `Ahora sigues a ${name}.`,
    actionCouldNotBeCompleted: 'No se pudo completar la acción.',
    fileTooLarge: 'Archivo Demasiado Grande',
    imageTooLargeDesc: 'La imagen debe ser más pequeña de 5MB.',
    newAvatarSaved: 'Tu nuevo avatar ha sido guardado.',
    newCoverSaved: 'Tu nueva foto de portada ha sido guardada.',
    uploadFailed: 'Subida Fallida',
    couldNotUploadImage: 'No se pudo subir tu imagen.',
    couldNotFetchProfile: 'No se pudo obtener el usuario del perfil.',
    couldNotFetchUserPosts: 'No se pudieron obtener las publicaciones del usuario. Es posible que necesites crear un índice en Firestore.',
    couldNotFetchSavedPosts: 'No se pudieron obtener las publicaciones guardadas.',
    loggedIn: '¡Sesión iniciada con éxito! Redirigiendo...',
    loginFailed: 'Inicio de Sesión Fallido',
    googleLoginFailed: 'No se pudo iniciar la sesión con Google. Por favor, inténtalo de nuevo.',
    accountCreated: '¡Cuenta creada con éxito!',
    signupFailed: 'Registro Fallido',
    passwordLengthError: 'La contraseña debe tener al menos 6 caracteres.',
    googleSignupFailed: 'No se pudo iniciar el registro con Google. Por favor, inténtalo de nuevo.',
    notAuthenticated: 'No Autenticado',
    mustBeLoggedIn: 'Debes iniciar sesión para crear una publicación.',
    postError: 'Error de Publicación',
    couldNotCreatePost: 'No se pudo crear la publicación.',
    invalidFile: 'Archivo Inválido',
    invalidImageFile: 'Por favor, selecciona un archivo de imagen (jpg, png, gif, webp).',
    invalidVideoFile: 'Por favor, selecciona un archivo de video (mp4, webm, ogg).',
    fileTooLarge20MB: 'El archivo debe ser más pequeño de 20MB.',
    postPublished: 'Tu publicación ha sido publicada.',
    uploadError: 'Error de Subida',
    loggedOut: 'Sesión Cerrada',
    loggedOutDesc: 'Has cerrado sesión correctamente.',
    logoutError: 'No se pudo cerrar sesión.',
    postReported: 'Publicación Reportada',
    reportThanks: 'Gracias por tus comentarios. Revisaremos esta publicación.',
    couldNotSubmitReport: 'No se pudo enviar tu reporte.',
    mustBeLoggedInToComment: 'Debes iniciar sesión para comentar.',
    couldNotAddComment: 'No se pudo añadir el comentario.',
    authError: 'Error de Autenticación',
    mustBeLoggedInToLike: 'Debes iniciar sesión para dar "me gusta" a una publicación.',
    couldNotUpdateLike: 'No se pudo actualizar el "me gusta".',
    mustBeLoggedInToSave: 'Debes iniciar sesión para guardar una publicación.',
    postUnsaved: 'Publicación no Guardada',
    postUnsavedDesc: 'Eliminado de tus publicaciones guardadas.',
    postSaved: 'Publicación Guardada',
    postSavedDesc: 'Añadido a tus publicaciones guardadas.',
    couldNotSavePost: 'No se pudo guardar la publicación.',
    unauthorized: 'No Autorizado',
    unauthorizedDelete: 'Solo puedes eliminar tus propias publicaciones.',
    // Facebook Video Warnings
    unsupportedFacebookLink: 'Enlace de Facebook No Compatible',
    unsupportedFacebookLinkDesc: 'Este formato de enlace no es compatible. Por favor, copie el enlace de video directo desde la página principal del video.',
    correctLinkFormats: 'Formatos de enlace correctos:',
    videoPageInstructions: 'Vaya a la página del video y copie la URL directa del video.',
    // Admin Panel
    adminDashboard: 'Panel de Administración',
    adminWelcome: 'Bienvenido al centro de control de administración.',
    totalUsers: 'Total de Usuarios',
    totalPosts: 'Total de Publicaciones',
    reportedPosts: 'Publicaciones Reportadas',
    bannedPosts: 'Publicaciones Prohibidas',
    storageUsage: 'Uso de Almacenamiento',
    storageUsageDesc: 'Uso mensual del almacenamiento en la nube.',
    storageUsageDetail: (usedGb: string, percentage: string, limitGb: number) => `El uso mensual es de ${usedGb} GB (${percentage}%) del límite de ${limitGb} GB.`,
    usedStorage: 'Usado',
    remainingStorage: 'Restante',
    quickActions: 'Acciones Rápidas',
    quickActionsDesc: 'Realiza tareas administrativas comunes.',
    sendGlobalNotification: 'Enviar Notificación Global',
    recalculateStats: 'Recalcular Todas las Estadísticas',
    disableSite: 'Desactivar Sitio Temporalmente',
    postManagement: 'Gestión de Publicaciones',
    postManagementDesc: 'Ver y gestionar todas las publicaciones de los usuarios. Puedes prohibir, desprohibir o eliminar publicaciones.',
    author: 'Autor',
    content: 'Contenido',
    reports: 'Reportes',
    status: 'Status',
    created: 'Creado',
    actions: 'Acciones',
    unknownUser: 'Usuario Desconocido',
    mediaPost: 'Publicación Multimedia',
    banPost: 'Prohibir Publicación',
    unbanPost: 'Desprohibir Publicación',
    userManagement: 'Gestión de Usuarios',
    userManagementDesc: 'Ver y gestionar todos los usuarios registrados.',
    user: 'Usuario',
    email: 'Correo Electrónico',
    joined: 'Se unió',
    deleteUser: 'Eliminar Usuario',
};

const fr: typeof en = {
    home: 'Accueil',
    explore: 'Explorer',
    notifications: 'Notifications',
    profile: 'Profil',
    createPost: 'Créer une publication',
    settings: 'Paramètres',
    appearance: 'Apparence',
    toggleTheme: 'Changer de thème',
    colorTheme: 'Thème de couleur',
    language: 'Langue',
    logout: 'Se déconnecter',
    whatsOnYourMind: 'À quoi pensez-vous ?',
    shareWithCommunity: "Partagez vos pensées, photos, vidéos ou liens avec la communauté.",
    writePostPlaceholder: "Que se passe-t-il ? #hashtag",
    selectImageToUpload: 'Sélectionnez une image à télécharger',
    selectVideoToUpload: 'Sélectionnez une vidéo à télécharger',
    post: 'Publier',
    posting: 'Publication...',
    linkUrlPlaceholder: 'Entrez le lien à partager',
    save: 'Enregistrer',
    saved: 'Enregistré',
    reportPost: 'Signaler la publication',
    reportDescription: 'Veuillez fournir une raison pour signaler cette publication. Vos commentaires sont importants pour la sécurité de la communauté.',
    reportPlaceholder: 'par ex. spam, contenu inapproprié, harcèlement...',
    cancel: 'Annuler',
    submitReport: 'Soumettre le signalement',
    deletePost: 'Supprimer la publication',
    createNewPost: 'Créer une nouvelle publication',
    welcomeToUmmahConnect: 'Bienvenue sur UmmahConnect !',
    writeAComment: 'Écrivez un commentaire...',
    send: 'Envoyer',
    // Explore Page
    exploreDescription: 'Découvrez le contenu le plus populaire de la communauté.',
    mostLikedPosts: 'Publications les plus aimées',
    mostCommentedPosts: 'Publications les plus commentées',
    noImagePostsToExplore: 'Aucune publication avec image à explorer pour le moment.',
    // Notifications Page
    noNewNotifications: 'Vous n\'avez aucune nouvelle notification.',
    // Profile Page
    following: 'Abonnements',
    followers: 'Abonnés',
    follow: 'Suivre',
    message: 'Message',
    posts: 'Publications',
    replies: 'Réponses',
    likes: 'J\'aime',
    noPostsYet: 'Aucune publication pour le moment.',
    noRepliesYet: 'Aucune réponse pour le moment.',
    noLikesYet: 'Aucun "j\'aime" pour le moment.',
    savedPostsArePrivate: 'Les publications enregistrées sont privées.',
    youHaventSavedPosts: 'Vous n\'avez encore enregistré aucune publication.',
    youHaventRepliedYet: "Vous n'avez encore répondu à aucune publication.",
    youHaventLikedYet: "Vous n'avez encore aimé aucune publication.",
    // Toasts & Alerts
    error: 'Erreur',
    success: 'Succès',
    couldNotFetchDashboardStats: 'Impossible de récupérer les statistiques du tableau de bord.',
    userDeleted: 'Utilisateur Supprimé',
    userDeletedDesc: (name: string) => `${name} a été supprimé avec succès.`,
    couldNotDeleteUser: 'Impossible de supprimer l\'utilisateur. Vérifiez les règles de Firestore.',
    postUpdated: 'Publication Mise à Jour',
    postUpdatedDesc: (status: 'banned' | 'active') => `La publication a été ${status === 'banned' ? 'bannie' : 'débannie'}.`,
    couldNotUpdatePost: 'Impossible de mettre à jour le statut de la publication.',
    postDeleted: 'Publication Supprimée',
    postDeletedDesc: 'La publication a été supprimée avec succès.',
    couldNotDeletePost: 'Impossible de supprimer la publication. Vérifiez les règles de Firestore.',
    couldNotFetchPosts: 'Impossible de récupérer les publications. Vous devrez peut-être créer des index Firestore.',
    unfollowed: 'Désabonné',
    unfollowedDesc: (name: string) => `Vous ne suivez plus ${name}.`,
    followed: 'Abonné',
    followedDesc: (name: string) => `Vous suivez maintenant ${name}.`,
    actionCouldNotBeCompleted: 'L\'action n\'a pas pu être terminée.',
    fileTooLarge: 'Fichier Trop Volumineux',
    imageTooLargeDesc: 'L\'image doit être inférieure à 5 Mo.',
    newAvatarSaved: 'Votre nouvel avatar a été enregistré.',
    newCoverSaved: 'Votre nouvelle photo de couverture a été enregistrée.',
    uploadFailed: 'Échec du Téléchargement',
    couldNotUploadImage: 'Impossible de télécharger votre image.',
    couldNotFetchProfile: 'Impossible de récupérer l\'utilisateur du profil.',
    couldNotFetchUserPosts: 'Impossible de récupérer les publications de l\'utilisateur. Vous devrez peut-être créer un index dans Firestore.',
    couldNotFetchSavedPosts: 'Impossible de récupérer les publications enregistrées.',
    loggedIn: 'Connecté avec succès ! Redirection...',
    loginFailed: 'Échec de la Connexion',
    googleLoginFailed: 'Impossible d\'initier la connexion Google. Veuillez réessayer.',
    accountCreated: 'Compte créé avec succès !',
    signupFailed: 'Échec de l\'Inscription',
    passwordLengthError: 'Le mot de passe doit comporter au moins 6 caractères.',
    googleSignupFailed: 'Impossible d\'initier l\'inscription Google. Veuillez réessayer.',
    notAuthenticated: 'Non Authentifié',
    mustBeLoggedIn: 'Vous devez être connecté pour créer une publication.',
    postError: 'Erreur de Publication',
    couldNotCreatePost: 'Impossible de créer la publication.',
    invalidFile: 'Fichier Invalide',
    invalidImageFile: 'Veuillez sélectionner un fichier image (jpg, png, gif, webp).',
    invalidVideoFile: 'Veuillez sélectionner un fichier vidéo (mp4, webm, ogg).',
    fileTooLarge20MB: 'Le fichier doit être inférieur à 20 Mo.',
    postPublished: 'Votre publication a été publiée.',
    uploadError: 'Erreur de Téléchargement',
    loggedOut: 'Déconnecté',
    loggedOutDesc: 'Vous avez été déconnecté avec succès.',
    logoutError: 'Échec de la déconnexion.',
    postReported: 'Publication Signalée',
    reportThanks: 'Merci pour vos commentaires. Nous examinerons cette publication.',
    couldNotSubmitReport: 'Impossible de soumettre votre signalement.',
    mustBeLoggedInToComment: 'Vous devez être connecté pour commenter.',
    couldNotAddComment: 'Impossible d\'ajouter le commentaire.',
    authError: 'Erreur d\'Authentification',
    mustBeLoggedInToLike: 'Vous devez être connecté pour aimer une publication.',
    couldNotUpdateLike: 'Impossible de mettre à jour le "j\'aime".',
    mustBeLoggedInToSave: 'Vous devez être connecté pour enregistrer une publication.',
    postUnsaved: 'Publication Désenregistrée',
    postUnsavedDesc: 'Retiré de vos publications enregistrées.',
    postSaved: 'Publication Enregistrée',
    postSavedDesc: 'Ajouté à vos publications enregistrées.',
    couldNotSavePost: 'Impossible d\'enregistrer la publication.',
    unauthorized: 'Non Autorisé',
    unauthorizedDelete: 'Vous ne pouvez supprimer que vos propres publications.',
    // Facebook Video Warnings
    unsupportedFacebookLink: 'Lien Facebook Non Pris en Charge',
    unsupportedFacebookLinkDesc: 'Ce format de lien n\'est pas pris en charge. Veuillez copier le lien vidéo direct depuis la page principale de la vidéo.',
    correctLinkFormats: 'Formats de lien corrects :',
    videoPageInstructions: 'Allez sur la page de la vidéo et copiez l URL directe de la vidéo.',
    // Admin Panel
    adminDashboard: "Tableau de bord d'administration",
    adminWelcome: "Bienvenue dans le centre de contrôle d'administration.",
    totalUsers: 'Total des utilisateurs',
    totalPosts: 'Total des publications',
    reportedPosts: 'Publications signalées',
    bannedPosts: 'Publications bannies',
    storageUsage: 'Utilisation du stockage',
    storageUsageDesc: "Utilisation mensuelle du stockage cloud.",
    storageUsageDetail: (usedGb: string, percentage: string, limitGb: number) => `L'utilisation mensuelle est de ${usedGb} Go (${percentage} %) sur la limite de ${limitGb} Go.`,
    usedStorage: 'Utilisé',
    remainingStorage: 'Restant',
    quickActions: 'Actions rapides',
    quickActionsDesc: 'Effectuez des tâches administratives courantes.',
    sendGlobalNotification: 'Envoyer une notification globale',
    recalculateStats: 'Recalculer toutes les statistiques',
    disableSite: 'Désactiver temporairement le site',
    postManagement: 'Gestion des publications',
    postManagementDesc: 'Affichez et gérez toutes les publications des utilisateurs. Vous pouvez bannir, débannir ou supprimer des publications.',
    author: 'Auteur',
    content: 'Contenu',
    reports: 'Rapports',
    status: 'Statut',
    created: 'Créé',
    actions: 'Actions',
    unknownUser: 'Utilisateur inconnu',
    mediaPost: 'Publication multimédia',
    banPost: 'Bannir la publication',
    unbanPost: 'Débannir la publication',
    userManagement: 'Gestion des utilisateurs',
    userManagementDesc: 'Affichez et gérez tous les utilisateurs enregistrés.',
    user: 'Utilisateur',
    email: 'E-mail',
    joined: 'Rejoint le',
    deleteUser: "Supprimer l'utilisateur",
};

const ar: typeof en = {
    home: 'الرئيسية',
    explore: 'استكشف',
    notifications: 'الإشعارات',
    profile: 'الملف الشخصي',
    createPost: 'إنشاء منشور',
    settings: 'الإعدادات',
    appearance: 'المظهر',
    toggleTheme: 'تبديل السمة',
    colorTheme: 'سمة اللون',
    language: 'اللغة',
    logout: 'تسجيل الخروج',
    whatsOnYourMind: 'بماذا تفكر؟',
    shareWithCommunity: "شارك أفكارك وصورك ومقاطع الفيديو أو الروابط مع المجتمع.",
    writePostPlaceholder: "ماذا يحدث؟ #علامة_تبويب",
    selectImageToUpload: 'اختر صورة للتحميل',
    selectVideoToUpload: 'اختر فيديو للتحميل',
    post: 'نشر',
    posting: 'جارٍ النشر...',
    linkUrlPlaceholder: 'أدخل الرابط للمشاركة',
    save: 'حفظ',
    saved: 'محفوظ',
    reportPost: 'الإبلاغ عن المنشور',
    reportDescription: 'يرجى تقديم سبب للإبلاغ عن هذا المنشور. ملاحظاتك مهمة لسلامة المجتمع.',
    reportPlaceholder: 'مثال: بريد مزعج، محتوى غير لائق، مضايقة...',
    cancel: 'إلغاء',
    submitReport: 'إرسال البلاغ',
    deletePost: 'حذف المنشور',
    createNewPost: 'إنشاء منشور جديد',
    welcomeToUmmahConnect: 'أهلاً بك في UmmahConnect!',
    writeAComment: 'اكتب تعليقًا...',
    send: 'إرسال',
    // Explore Page
    exploreDescription: 'اكتشف المحتوى الأكثر شيوعًا في المجتمع.',
    mostLikedPosts: 'المنشورات الأكثر إعجابًا',
    mostCommentedPosts: 'المنشورات الأكثر تعليقًا',
    noImagePostsToExplore: 'لا توجد منشورات صور لاستكشافها بعد.',
    // Notifications Page
    noNewNotifications: 'ليس لديك إشعارات جديدة.',
    // Profile Page
    following: 'متابَع',
    followers: 'متابعون',
    follow: 'متابعة',
    message: 'رسالة',
    posts: 'المنشورات',
    replies: 'الردود',
    likes: 'الإعجابات',
    noPostsYet: 'لا توجد منشورات بعد.',
    noRepliesYet: 'لا توجد ردود بعد.',
    noLikesYet: 'لا توجد إعجابات بعد.',
    savedPostsArePrivate: 'المنشورات المحفوظة خاصة.',
    youHaventSavedPosts: 'لم تحفظ أي منشورات بعد.',
    youHaventRepliedYet: "لم ترد على أي منشورات بعد.",
    youHaventLikedYet: "لم تعجبك أي منشورات بعد.",
    // Toasts & Alerts
    error: 'خطأ',
    success: 'نجاح',
    couldNotFetchDashboardStats: 'تعذر جلب إحصائيات لوحة التحكم.',
    userDeleted: 'تم حذف المستخدم',
    userDeletedDesc: (name: string) => `${name} تم حذف ${name} بنجاح.`,
    couldNotDeleteUser: 'تعذر حذف المستخدم. تحقق من قواعد Firestore.',
    postUpdated: 'تم تحديث المنشور',
    postUpdatedDesc: (status: 'banned' | 'active') => `تم ${status === 'banned' ? 'حظر' : 'إلغاء حظر'} المنشور.`,
    couldNotUpdatePost: 'تعذر تحديث حالة المنشور.',
    postDeleted: 'تم حذف المنشور',
    postDeletedDesc: 'تم حذف المنشور بنجاح.',
    couldNotDeletePost: 'تعذر حذف المنشور. تحقق من قواعد Firestore.',
    couldNotFetchPosts: 'تعذر جلب المنشورات. قد تحتاج إلى إنشاء فهارس Firestore.',
    unfollowed: 'تم إلغاء المتابعة',
    unfollowedDesc: (name: string) => `لم تعد تتابع ${name}.`,
    followed: 'تمت المتابعة',
    followedDesc: (name: string) => `أنت تتابع الآن ${name}.`,
    actionCouldNotBeCompleted: 'تعذر إكمال الإجراء.',
    fileTooLarge: 'الملف كبير جدًا',
    imageTooLargeDesc: 'يجب أن يكون حجم الصورة أصغر من 5 ميجابايت.',
    newAvatarSaved: 'تم حفظ صورتك الرمزية الجديدة.',
    newCoverSaved: 'تم حفظ صورة الغلاف الجديدة.',
    uploadFailed: 'فشل التحميل',
    couldNotUploadImage: 'تعذر تحميل صورتك.',
    couldNotFetchProfile: 'تعذر جلب مستخدم الملف الشخصي.',
    couldNotFetchUserPosts: 'تعذر جلب منشورات المستخدم. قد تحتاج إلى إنشاء فهرس في Firestore.',
    couldNotFetchSavedPosts: 'تعذر جلب المنشورات المحفوظة.',
    loggedIn: 'تم تسجيل الدخول بنجاح! جارٍ إعادة التوجيه...',
    loginFailed: 'فشل تسجيل الدخول',
    googleLoginFailed: 'تعذر بدء تسجيل الدخول بحساب Google. يرجى المحاولة مرة أخرى.',
    accountCreated: 'تم إنشاء الحساب بنجاح!',
    signupFailed: 'فشل التسجيل',
    passwordLengthError: 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.',
    googleSignupFailed: 'تعذر بدء التسجيل بحساب Google. يرجى المحاولة مرة أخرى.',
    notAuthenticated: 'غير مصادق عليه',
    mustBeLoggedIn: 'يجب عليك تسجيل الدخول لإنشاء منشور.',
    postError: 'خطأ في النشر',
    couldNotCreatePost: 'تعذر إنشاء المنشور.',
    invalidFile: 'ملف غير صالح',
    invalidImageFile: 'يرجى تحديد ملف صورة (jpg, png, gif, webp).',
    invalidVideoFile: 'يرجى تحديد ملف فيديو (mp4, webm, ogg).',
    fileTooLarge20MB: 'يجب أن يكون حجم الملف أصغر من 20 ميجابايت.',
    postPublished: 'تم نشر منشورك.',
    uploadError: 'خطأ في التحميل',
    loggedOut: 'تم تسجيل الخروج',
    loggedOutDesc: 'لقد قمت بتسجيل الخروج بنجاح.',
    logoutError: 'فشل تسجيل الخروج.',
    postReported: 'تم الإبلاغ عن المنشور',
    reportThanks: 'شكرًا لملاحظاتك. سنراجع هذا المنشور.',
    couldNotSubmitReport: 'تعذر إرسال بلاغك.',
    mustBeLoggedInToComment: 'يجب عليك تسجيل الدخول للتعليق.',
    couldNotAddComment: 'تعذر إضافة التعليق.',
    authError: 'خطأ في المصادقة',
    mustBeLoggedInToLike: 'يجب عليك تسجيل الدخول للإعجاب بمنشور.',
    couldNotUpdateLike: 'تعذر تحديث الإعجاب.',
    mustBeLoggedInToSave: 'يجب عليك تسجيل الدخول لحفظ منشور.',
    postUnsaved: 'تم إلغاء حفظ المنشور',
    postUnsavedDesc: 'تمت إزالته من منشوراتك المحفوظة.',
    postSaved: 'تم حفظ المنشور',
    postSavedDesc: 'تمت إضافته إلى منشوراتك المحفوظة.',
    couldNotSavePost: 'تعذر حفظ المنشور.',
    unauthorized: 'غير مصرح به',
    unauthorizedDelete: 'يمكنك فقط حذف منشوراتك الخاصة.',
    // Facebook Video Warnings
    unsupportedFacebookLink: 'رابط فيسبوك غير مدعوم',
    unsupportedFacebookLinkDesc: 'تنسيق الرابط هذا غير مدعوم. يرجى نسخ رابط الفيديو المباشر من الصفحة الرئيسية للفيديو.',
    correctLinkFormats: 'تنسيقات الروابط الصحيحة:',
    videoPageInstructions: 'اذهب إلى صفحة الفيديو وانسخ رابط الفيديو المباشر.',
    // Admin Panel
    adminDashboard: 'لوحة تحكم المشرف',
    adminWelcome: 'مرحبًا بك في مركز تحكم المشرف.',
    totalUsers: 'إجمالي المستخدمين',
    totalPosts: 'إجمالي المشاركات',
    reportedPosts: 'المشاركات المبلغ عنها',
    bannedPosts: 'المشاركات المحظورة',
    storageUsage: 'استخدام التخزين',
    storageUsageDesc: 'استخدام التخزين السحابي الشهري.',
    storageUsageDetail: (usedGb: string, percentage: string, limitGb: number) => `الاستخدام الشهري هو ${usedGb} جيجابايت (${percentage}٪) من حد ${limitGb} جيجابايت.`,
    usedStorage: 'مستخدم',
    remainingStorage: 'متبقي',
    quickActions: 'إجراءات سريعة',
    quickActionsDesc: 'قم بتنفيذ المهام الإدارية الشائعة.',
    sendGlobalNotification: 'إرسال إشعار عالمي',
    recalculateStats: 'إعادة حساب جميع الإحصائيات',
    disableSite: 'تعطيل الموقع مؤقتًا',
    postManagement: 'إدارة المشاركات',
    postManagementDesc: 'عرض وإدارة جميع مشاركات المستخدمين. يمكنك حظر المشاركات أو إلغاء حظرها أو حذفها.',
    author: 'المؤلف',
    content: 'المحتوى',
    reports: 'التقارير',
    status: 'الحالة',
    created: 'تم إنشاؤه',
    actions: 'الإجراءات',
    unknownUser: 'مستخدم غير معروف',
    mediaPost: 'مشاركة وسائط',
    banPost: 'حظر المشاركة',
    unbanPost: 'إلغاء حظر المشاركة',
    userManagement: 'إدارة المستخدمين',
    userManagementDesc: 'عرض وإدارة جميع المستخدمين المسجلين.',
    user: 'المستخدم',
    email: 'البريد الإلكتروني',
    joined: 'انضم',
    deleteUser: 'حذف المستخدم',
};

const hi: typeof en = {
    home: 'होम',
    explore: 'अन्वेषण करें',
    notifications: 'सूचनाएं',
    profile: 'प्रोफ़ाइल',
    createPost: 'पोस्ट बनाएं',
    settings: 'सेटिंग्स',
    appearance: 'दिखावट',
    toggleTheme: 'थीम बदलें',
    colorTheme: 'रंग थीम',
    language: 'भाषा',
    logout: 'लॉग आउट',
    whatsOnYourMind: 'आपके मन में क्या है?',
    shareWithCommunity: "अपने विचार, फ़ोटो, वीडियो या लिंक समुदाय के साथ साझा करें।",
    writePostPlaceholder: "क्या हो रहा है? #हैशटैग",
    selectImageToUpload: 'अपलोड करने के लिए एक छवि चुनें',
    selectVideoToUpload: 'अपलोड करने के लिए एक वीडियो चुनें',
    post: 'पोस्ट करें',
    posting: 'पोस्ट किया जा रहा है...',
    linkUrlPlaceholder: 'साझा करने के लिए लिंक दर्ज करें',
    save: 'सहेजें',
    saved: 'सहेजा गया',
    reportPost: 'पोस्ट की रिपोर्ट करें',
    reportDescription: 'कृपया इस पोस्ट की रिपोर्ट करने का कारण बताएं। आपकी प्रतिक्रिया समुदाय की सुरक्षा के लिए महत्वपूर्ण है।',
    reportPlaceholder: 'उदा. स्पैम, अनुचित सामग्री, उत्पीड़न...',
    cancel: 'रद्द करें',
    submitReport: 'रिपोर्ट सबमिट करें',
    deletePost: 'पोस्ट हटाएं',
    createNewPost: 'एक नई पोस्ट बनाएं',
    welcomeToUmmahConnect: 'UmmahConnect में आपका स्वागत है!',
    writeAComment: 'एक टिप्पणी लिखें...',
    send: 'भेजें',
    // Explore Page
    exploreDescription: 'समुदाय से सबसे लोकप्रिय सामग्री खोजें।',
    mostLikedPosts: 'सबसे ज्यादा पसंद की गई पोस्ट',
    mostCommentedPosts: 'सबसे ज्यादा टिप्पणी की गई पोस्ट',
    noImagePostsToExplore: 'अभी तक एक्सप्लोर करने के लिए कोई इमेज पोस्ट नहीं है।',
    // Notifications Page
    noNewNotifications: 'आपके पास कोई नई सूचना नहीं है।',
    // Profile Page
    following: 'फॉलो कर रहे हैं',
    followers: 'फॉलोअर्स',
    follow: 'फॉलो करें',
    message: 'संदेश',
    posts: 'पोस्ट',
    replies: 'उत्तर',
    likes: 'लाइक',
    noPostsYet: 'अभी तक कोई पोस्ट नहीं है।',
    noRepliesYet: 'अभी तक कोई उत्तर नहीं है।',
    noLikesYet: 'अभी तक कोई लाइक नहीं है।',
    savedPostsArePrivate: 'सहेजी गई पोस्ट निजी हैं।',
    youHaventSavedPosts: 'आपने अभी तक कोई पोस्ट नहीं सहेजी है।',
    youHaventRepliedYet: "आपने अभी तक किसी भी पोस्ट का जवाब नहीं दिया है।",
    youHaventLikedYet: "आपने अभी तक किसी भी पोस्ट को लाइक नहीं किया है।",
    // Toasts & Alerts
    error: 'त्रुटि',
    success: 'सफलता',
    couldNotFetchDashboardStats: 'डैशबोर्ड आँकड़े प्राप्त नहीं किए जा सके।',
    userDeleted: 'उपयोगकर्ता हटाया गया',
    userDeletedDesc: (name: string) => `${name} को सफलतापूर्वक हटा दिया गया है।`,
    couldNotDeleteUser: 'उपयोगकर्ता को हटाया नहीं जा सका। फायरस्टोर नियमों की जाँच करें।',
    postUpdated: 'पोस्ट अपडेट किया गया',
    postUpdatedDesc: (status: 'banned' | 'active') => `पोस्ट को ${status === 'banned' ? 'प्रतिबंधित' : 'अप्रतिबंधित'} कर दिया गया है।`,
    couldNotUpdatePost: 'पोस्ट स्थिति को अपडेट नहीं किया जा सका।',
    postDeleted: 'पोस्ट हटाया गया',
    postDeletedDesc: 'पोस्ट को सफलतापूर्वक हटा दिया गया है।',
    couldNotDeletePost: 'पोस्ट को हटाया नहीं जा सका। फायरस्टोर नियमों की जाँच करें।',
    couldNotFetchPosts: 'पोस्ट प्राप्त नहीं किए जा सके। आपको फायरस्टोर इंडेक्स बनाने की आवश्यकता हो सकती है।',
    unfollowed: 'अनफॉलो किया गया',
    unfollowedDesc: (name: string) => `आप अब ${name} को फॉलो नहीं कर रहे हैं।`,
    followed: 'फॉलो किया गया',
    followedDesc: (name: string) => `अब आप ${name} को फॉलो कर रहे हैं।`,
    actionCouldNotBeCompleted: 'कार्रवाई पूरी नहीं की जा सकी।',
    fileTooLarge: 'फ़ाइल बहुत बड़ी है',
    imageTooLargeDesc: 'छवि 5MB से छोटी होनी चाहिए।',
    newAvatarSaved: 'आपका नया अवतार सहेजा गया है।',
    newCoverSaved: 'आपकी नई कवर फ़ोटो सहेजी गई है।',
    uploadFailed: 'अपलोड विफल',
    couldNotUploadImage: 'आपकी छवि अपलोड नहीं की जा सकी।',
    couldNotFetchProfile: 'प्रोफ़ाइल उपयोगकर्ता को प्राप्त नहीं किया जा सका।',
    couldNotFetchUserPosts: 'उपयोगकर्ता पोस्ट प्राप्त नहीं किए जा सके। आपको फायरस्टोर में एक इंडेक्स बनाने की आवश्यकता हो सकती है।',
    couldNotFetchSavedPosts: 'सहेजे गए पोस्ट प्राप्त नहीं किए जा सके।',
    loggedIn: 'सफलतापूर्वक लॉग इन किया गया! रीडायरेक्ट किया जा रहा है...',
    loginFailed: 'लॉगिन विफल',
    googleLoginFailed: 'Google लॉगिन प्रारंभ नहीं किया जा सका। कृपया पुनः प्रयास करें।',
    accountCreated: 'खाता सफलतापूर्वक बनाया गया!',
    signupFailed: 'साइन अप विफल',
    passwordLengthError: 'पासवर्ड कम से कम 6 वर्णों का होना चाहिए।',
    googleSignupFailed: 'Google साइन अप प्रारंभ नहीं किया जा सका। कृपया पुनः प्रयास करें।',
    notAuthenticated: 'प्रमाणित नहीं',
    mustBeLoggedIn: 'पोस्ट बनाने के लिए आपको लॉग इन होना चाहिए।',
    postError: 'पोस्ट त्रुटि',
    couldNotCreatePost: 'पोस्ट नहीं बनाया जा सका।',
    invalidFile: 'अमान्य फ़ाइल',
    invalidImageFile: 'कृपया एक छवि फ़ाइल (jpg, png, gif, webp) चुनें।',
    invalidVideoFile: 'कृपया एक वीडियो फ़ाइल (mp4, webm, ogg) चुनें।',
    fileTooLarge20MB: 'फ़ाइल 20MB से छोटी होनी चाहिए।',
    postPublished: 'आपकी पोस्ट प्रकाशित हो गई है।',
    uploadError: 'अपलोड त्रुटि',
    loggedOut: 'लॉग आउट',
    loggedOutDesc: 'आप सफलतापूर्वक लॉग आउट हो गए हैं।',
    logoutError: 'लॉग आउट करने में विफल।',
    postReported: 'पोस्ट की रिपोर्ट की गई',
    reportThanks: 'आपकी प्रतिक्रिया के लिए धन्यवाद। हम इस पोस्ट की समीक्षा करेंगे।',
    couldNotSubmitReport: 'आपकी रिपोर्ट सबमिट नहीं की जा सकी।',
    mustBeLoggedInToComment: 'टिप्पणी करने के लिए आपको लॉग इन होना चाहिए।',
    couldNotAddComment: 'टिप्पणी नहीं जोड़ी जा सकी।',
    authError: 'प्रमाणीकरण त्रुटि',
    mustBeLoggedInToLike: 'पोस्ट को लाइक करने के लिए आपको लॉग इन होना चाहिए।',
    couldNotUpdateLike: 'लाइक अपडेट नहीं किया जा सका।',
    mustBeLoggedInToSave: 'पोस्ट को सहेजने के लिए आपको लॉग इन होना चाहिए।',
    postUnsaved: 'पोस्ट सहेजा नहीं गया',
    postUnsavedDesc: 'आपके सहेजे गए पोस्ट से हटाया गया।',
    postSaved: 'पोस्ट सहेजा गया',
    postSavedDesc: 'आपके सहेजे गए पोस्ट में जोड़ा गया।',
    couldNotSavePost: 'पोस्ट सहेजा नहीं जा सका।',
    unauthorized: 'अनधिकृत',
    unauthorizedDelete: 'आप केवल अपनी पोस्ट हटा सकते हैं।',
    // Facebook Video Warnings
    unsupportedFacebookLink: 'असमर्थित फेसबुक लिंक',
    unsupportedFacebookLinkDesc: 'यह लिंक प्रारूप समर्थित नहीं है। कृपया वीडियो के मुख्य पृष्ठ से प्रत्यक्ष वीडियो लिंक कॉपी करें।',
    correctLinkFormats: 'सही लिंक प्रारूप:',
    videoPageInstructions: 'वीडियो पृष्ठ पर जाएं और प्रत्यक्ष वीडियो URL कॉपी करें।',
    // Admin Panel
    adminDashboard: 'एडमिन डैशबोर्ड',
    adminWelcome: 'एडमिन कंट्रोल सेंटर में आपका स्वागत है।',
    totalUsers: 'कुल उपयोगकर्ता',
    totalPosts: 'कुल पोस्ट',
    reportedPosts: 'रिपोर्ट की गई पोस्ट',
    bannedPosts: 'प्रतिबंधित पोस्ट',
    storageUsage: 'भंडारण उपयोग',
    storageUsageDesc: 'मासिक क्लाउड भंडारण उपयोग।',
    storageUsageDetail: (usedGb: string, percentage: string, limitGb: number) => `मासिक उपयोग ${usedGb} जीबी (${percentage}%) है ${limitGb} जीबी सीमा का।`,
    usedStorage: 'उपयोग किया गया',
    remainingStorage: 'शेष',
    quickActions: 'त्वरित कार्रवाइयां',
    quickActionsDesc: 'सामान्य प्रशासनिक कार्य करें।',
    sendGlobalNotification: 'वैश्विक अधिसूचना भेजें',
    recalculateStats: 'सभी आँकड़े पुनर्गणना करें',
    disableSite: 'साइट को अस्थायी रूप से अक्षम करें',
    postManagement: 'पोस्ट प्रबंधन',
    postManagementDesc: 'सभी उपयोगकर्ता पोस्ट देखें और प्रबंधित करें। आप पोस्ट को प्रतिबंधित, अप्रतिबंधित या हटा सकते हैं।',
    author: 'लेखक',
    content: 'सामग्री',
    reports: 'रिपोर्ट',
    status: 'स्थिति',
    created: 'बनाया गया',
    actions: 'कार्रवाइयां',
    unknownUser: 'अज्ञात उपयोगकर्ता',
    mediaPost: 'मीडिया पोस्ट',
    banPost: 'पोस्ट प्रतिबंधित करें',
    unbanPost: 'पोस्ट अप्रतिबंधित करें',
    userManagement: 'उपयोगकर्ता प्रबंधन',
    userManagementDesc: 'सभी पंजीकृत उपयोगकर्ताओं को देखें और प्रबंधित करें।',
    user: 'उपयोगकर्ता',
    email: 'ईमेल',
    joined: 'शामिल हुए',
    deleteUser: 'उपयोगकर्ता हटाएं',
};

const bn: typeof en = {
    home: 'হোম',
    explore: 'অন্বেষণ',
    notifications: 'বিজ্ঞপ্তি',
    profile: 'প্রোফাইল',
    createPost: 'পোস্ট তৈরি করুন',
    settings: 'সেটিংস',
    appearance: 'চেহারা',
    toggleTheme: 'থিম পরিবর্তন করুন',
    colorTheme: 'রঙের থিম',
    language: 'ভাষা',
    logout: 'লগ আউট',
    whatsOnYourMind: 'আপনার মনে কি আছে?',
    shareWithCommunity: "আপনার চিন্তাভাবনা, ছবি, ভিডিও বা লিঙ্ক সম্প্রদায়ের সাথে শেয়ার করুন।",
    writePostPlaceholder: "কী ঘটছে? #হ্যাশট্যাগ",
    selectImageToUpload: 'আপলোড করার জন্য একটি ছবি নির্বাচন করুন',
    selectVideoToUpload: 'আপলোড করার জন্য একটি ভিডিও নির্বাচন করুন',
    post: 'পোস্ট করুন',
    posting: 'পোস্ট করা হচ্ছে...',
    linkUrlPlaceholder: 'শেয়ার করার জন্য লিঙ্ক লিখুন',
    save: 'সংরক্ষণ',
    saved: 'সংরক্ষিত',
    reportPost: 'পোস্ট রিপোর্ট করুন',
    reportDescription: 'এই পোস্টটি রিপোর্ট করার একটি কারণ প্রদান করুন। আপনার মতামত সম্প্রদায়ের সুরক্ষার জন্য গুরুত্বপূর্ণ।',
    reportPlaceholder: 'যেমন স্প্যাম, অনুপযুক্ত বিষয়বস্তু, হয়রানি...',
    cancel: 'বাতিল করুন',
    submitReport: 'রিপোর্ট জমা দিন',
    deletePost: 'পোস্ট মুছুন',
    createNewPost: 'একটি নতুন পোস্ট তৈরি করুন',
    welcomeToUmmahConnect: 'UmmahConnect-এ স্বাগতম!',
    writeAComment: 'একটি মন্তব্য লিখুন...',
    send: 'পাঠান',
    // Explore Page
    exploreDescription: 'সম্প্রদায়ের সবচেয়ে জনপ্রিয় বিষয়বস্তু আবিষ্কার করুন।',
    mostLikedPosts: 'সর্বাধিক লাইক করা পোস্ট',
    mostCommentedPosts: 'সর্বাধিক মন্তব্য করা পোস্ট',
    noImagePostsToExplore: 'এখনও অন্বেষণ করার জন্য কোনো ছবির পোস্ট নেই।',
    // Notifications Page
    noNewNotifications: 'আপনার কোনো নতুন বিজ্ঞপ্তি নেই।',
    // Profile Page
    following: 'অনুসরণ করছেন',
    followers: 'অনুসারী',
    follow: 'অনুসরণ করুন',
    message: 'বার্তা',
    posts: 'পোস্ট',
    replies: 'উত্তর',
    likes: 'লাইক',
    noPostsYet: 'এখনও কোনো পোস্ট নেই।',
    noRepliesYet: 'এখনও কোনো উত্তর নেই।',
    noLikesYet: 'এখনও কোনো লাইক নেই।',
    savedPostsArePrivate: 'সংরক্ষিত পোস্ট ব্যক্তিগত।',
    youHaventSavedPosts: 'আপনি এখনও কোনো পোস্ট সংরক্ষণ করেননি।',
    youHaventRepliedYet: "আপনি এখনও কোনো পোস্টে উত্তর দেননি।",
    youHaventLikedYet: "আপনি এখনও কোনো পোস্টে লাইক দেননি।",
    // Toasts & Alerts
    error: 'ত্রুটি',
    success: 'সাফল্য',
    couldNotFetchDashboardStats: 'ড্যাশবোর্ড পরিসংখ্যান আনা যায়নি।',
    userDeleted: 'ব্যবহারকারী মুছে ফেলা হয়েছে',
    userDeletedDesc: (name: string) => `${name} সফলভাবে মুছে ফেলা হয়েছে।`,
    couldNotDeleteUser: 'ব্যবহারকারী মুছে ফেলা যায়নি। ফায়ারস্টোর নিয়ম পরীক্ষা করুন।',
    postUpdated: 'পোস্ট আপডেট করা হয়েছে',
    postUpdatedDesc: (status: 'banned' | 'active') => `পোস্টটি ${status === 'banned' ? 'নিষিদ্ধ' : 'অনিষিদ্ধ'} করা হয়েছে।`,
    couldNotUpdatePost: 'পোস্টের স্থিতি আপডেট করা যায়নি।',
    postDeleted: 'পোস্ট মুছে ফেলা হয়েছে',
    postDeletedDesc: 'পোস্টটি সফলভাবে মুছে ফেলা হয়েছে।',
    couldNotDeletePost: 'পোস্ট মুছে ফেলা যায়নি। ফায়ারস্টোর নিয়ম পরীক্ষা করুন।',
    couldNotFetchPosts: 'পোস্ট আনা যায়নি। আপনাকে ফায়ারস্টোর সূচী তৈরি করতে হতে পারে।',
    unfollowed: 'আনফলো করা হয়েছে',
    unfollowedDesc: (name: string) => `আপনি আর ${name} কে অনুসরণ করছেন না।`,
    followed: 'অনুসরণ করা হয়েছে',
    followedDesc: (name: string) => `আপনি এখন ${name} কে অনুসরণ করছেন।`,
    actionCouldNotBeCompleted: 'ক্রিয়াটি সম্পন্ন করা যায়নি।',
    fileTooLarge: 'ফাইলটি খুব বড়',
    imageTooLargeDesc: 'ছবির আকার 5MB এর কম হতে হবে।',
    newAvatarSaved: 'আপনার নতুন অবতার সংরক্ষণ করা হয়েছে।',
    newCoverSaved: 'আপনার নতুন কভার ফটো সংরক্ষণ করা হয়েছে।',
    uploadFailed: 'আপলোড ব্যর্থ হয়েছে',
    couldNotUploadImage: 'আপনার ছবি আপলোড করা যায়নি।',
    couldNotFetchProfile: 'প্রোফাইল ব্যবহারকারী আনা যায়নি।',
    couldNotFetchUserPosts: 'ব্যবহারকারীর পোস্ট আনা যায়নি। আপনাকে ফায়ারস্টোরে একটি সূচী তৈরি করতে হতে পারে।',
    couldNotFetchSavedPosts: 'সংরক্ষিত পোস্ট আনা যায়নি।',
    loggedIn: 'সফলভাবে লগ ইন করা হয়েছে! পুনঃনির্দেশিত করা হচ্ছে...',
    loginFailed: 'লগইন ব্যর্থ হয়েছে',
    googleLoginFailed: 'Google লগইন শুরু করা যায়নি। অনুগ্রহ করে আবার চেষ্টা করুন।',
    accountCreated: 'অ্যাকাউন্ট সফলভাবে তৈরি করা হয়েছে!',
    signupFailed: 'সাইন আপ ব্যর্থ হয়েছে',
    passwordLengthError: 'পাসওয়ার্ড অন্তত 6 অক্ষরের হতে হবে।',
    googleSignupFailed: 'Google সাইন আপ শুরু করা যায়নি। অনুগ্রহ করে আবার চেষ্টা করুন।',
    notAuthenticated: 'প্রমাণিত নয়',
    mustBeLoggedIn: 'পোস্ট তৈরি করতে আপনাকে লগ ইন করতে হবে।',
    postError: 'পোস্ট ত্রুটি',
    couldNotCreatePost: 'পোস্ট তৈরি করা যায়নি।',
    invalidFile: 'অবৈধ ফাইল',
    invalidImageFile: 'অনুগ্রহ করে একটি ছবি ফাইল নির্বাচন করুন (jpg, png, gif, webp)।',
    invalidVideoFile: 'অনুগ্রহ করে একটি ভিডিও ফাইল নির্বাচন করুন (mp4, webm, ogg)।',
    fileTooLarge20MB: 'ফাইলের আকার 20MB এর কম হতে হবে।',
    postPublished: 'আপনার পোস্ট প্রকাশিত হয়েছে।',
    uploadError: 'আপলোড ত্রুটি',
    loggedOut: 'লগ আউট করা হয়েছে',
    loggedOutDesc: 'আপনি সফলভাবে লগ আউট করেছেন।',
    logoutError: 'লগ আউট করতে ব্যর্থ।',
    postReported: 'পোস্ট রিপোর্ট করা হয়েছে',
    reportThanks: 'আপনার মতামতের জন্য ধন্যবাদ। আমরা এই পোস্টটি পর্যালোচনা করব।',
    couldNotSubmitReport: 'আপনার রিপোর্ট জমা দেওয়া যায়নি।',
    mustBeLoggedInToComment: 'মন্তব্য করার জন্য আপনাকে লগ ইন করতে হবে।',
    couldNotAddComment: 'মন্তব্য যোগ করা যায়নি।',
    authError: 'প্রমাণীকরণ ত্রুটি',
    mustBeLoggedInToLike: 'একটি পোস্টে লাইক দিতে আপনাকে লগ ইন করতে হবে।',
    couldNotUpdateLike: 'লাইক আপডেট করা যায়নি।',
    mustBeLoggedInToSave: 'একটি পোস্ট সংরক্ষণ করতে আপনাকে লগ ইন করতে হবে।',
    postUnsaved: 'পোস্ট অসংরক্ষিত',
    postUnsavedDesc: 'আপনার সংরক্ষিত পোস্ট থেকে সরানো হয়েছে।',
    postSaved: 'পোস্ট সংরক্ষিত',
    postSavedDesc: 'আপনার সংরক্ষিত পোস্টে যোগ করা হয়েছে।',
    couldNotSavePost: 'পোস্ট সংরক্ষণ করা যায়নি।',
    unauthorized: 'অননুমোদিত',
    unauthorizedDelete: 'আপনি শুধুমাত্র আপনার নিজের পোস্ট মুছে ফেলতে পারেন।',
    // Facebook Video Warnings
    unsupportedFacebookLink: 'অসমর্থিত ফেসবুক লিঙ্ক',
    unsupportedFacebookLinkDesc: 'এই লিঙ্ক ফরম্যাট সমর্থিত নয়। অনুগ্রহ করে ভিডিওর মূল পৃষ্ঠা থেকে সরাসরি ভিডিও লিঙ্ক কপি করুন।',
    correctLinkFormats: 'সঠিক লিঙ্ক ফরম্যাট:',
    videoPageInstructions: 'ভিডিও পৃষ্ঠায় যান এবং সরাসরি ভিডিও URL কপি করুন।',
    // Admin Panel
    adminDashboard: 'অ্যাডমিন ড্যাশবোর্ড',
    adminWelcome: 'অ্যাডমিন নিয়ন্ত্রণ কেন্দ্রে স্বাগতম।',
    totalUsers: 'মোট ব্যবহারকারী',
    totalPosts: 'মোট পোস্ট',
    reportedPosts: 'রিপোর্ট করা পোস্ট',
    bannedPosts: 'নিষিদ্ধ পোস্ট',
    storageUsage: 'স্টোরেজ ব্যবহার',
    storageUsageDesc: 'মাসিক ক্লাউড স্টোরেজ ব্যবহার।',
    storageUsageDetail: (usedGb: string, percentage: string, limitGb: number) => `মাসিক ব্যবহার ${usedGb} জিবি (${percentage}%) ${limitGb} জিবি সীমার।`,
    usedStorage: 'ব্যবহৃত',
    remainingStorage: 'অবশিষ্ট',
    quickActions: 'দ্রুত ক্রিয়া',
    quickActionsDesc: 'সাধারণ প্রশাসনিক কাজ সম্পাদন করুন।',
    sendGlobalNotification: 'গ্লোবাল বিজ্ঞপ্তি পাঠান',
    recalculateStats: 'সমস্ত পরিসংখ্যান পুনরায় গণনা করুন',
    disableSite: 'অস্থায়ীভাবে সাইট নিষ্ক্রিয় করুন',
    postManagement: 'পোস্ট ম্যানেজমেন্ট',
    postManagementDesc: 'সমস্ত ব্যবহারকারীর পোস্ট দেখুন এবং পরিচালনা করুন। আপনি পোস্ট নিষিদ্ধ, অনিষিদ্ধ বা মুছে ফেলতে পারেন।',
    author: 'লেখক',
    content: 'বিষয়বস্তু',
    reports: 'রিপোর্ট',
    status: 'স্থিতি',
    created: 'তৈরি করা হয়েছে',
    actions: 'ক্রিয়া',
    unknownUser: 'অজানা ব্যবহারকারী',
    mediaPost: 'মিডিয়া পোস্ট',
    banPost: 'পোস্ট নিষিদ্ধ করুন',
    unbanPost: 'পোস্ট অনিষিদ্ধ করুন',
    userManagement: 'ব্যবহারকারী ম্যানেজমেন্ট',
    userManagementDesc: 'সমস্ত নিবন্ধিত ব্যবহারকারী দেখুন এবং পরিচালনা করুন।',
    user: 'ব্যবহারকারী',
    email: 'ইমেল',
    joined: 'যোগদান করেছেন',
    deleteUser: 'ব্যবহারকারী মুছুন',
};

const ru: typeof en = {
    home: 'Главная',
    explore: 'Исследовать',
    notifications: 'Уведомления',
    profile: 'Профиль',
    createPost: 'Создать пост',
    settings: 'Настройки',
    appearance: 'Внешний вид',
    toggleTheme: 'Сменить тему',
    colorTheme: 'Цветовая тема',
    language: 'Язык',
    logout: 'Выйти',
    whatsOnYourMind: 'О чем вы думаете?',
    shareWithCommunity: "Поделитесь своими мыслями, фотографиями, видео или ссылками с сообществом.",
    writePostPlaceholder: "Что происходит? #хештег",
    selectImageToUpload: 'Выберите изображение для загрузки',
    selectVideoToUpload: 'Выберите видео для загрузки',
    post: 'Опубликовать',
    posting: 'Публикация...',
    linkUrlPlaceholder: 'Введите ссылку, чтобы поделиться',
    save: 'Сохранить',
    saved: 'Сохранено',
    reportPost: 'Пожаловаться на публикацию',
    reportDescription: 'Пожалуйста, укажите причину жалобы на эту публикацию. Ваш отзыв важен для безопасности сообщества.',
    reportPlaceholder: 'например, спам, неприемлемый контент, преследование...',
    cancel: 'Отмена',
    submitReport: 'Отправить жалобу',
    deletePost: 'Удалить публикацию',
    createNewPost: 'Создать новую публикацию',
    welcomeToUmmahConnect: 'Добро пожаловать в UmmahConnect!',
    writeAComment: 'Напишите комментарий...',
    send: 'Отправить',
    // Explore Page
    exploreDescription: 'Откройте для себя самый популярный контент от сообщества.',
    mostLikedPosts: 'Самые популярные публикации',
    mostCommentedPosts: 'Самые комментируемые публикации',
    noImagePostsToExplore: 'Пока нет публикаций с изображениями для исследования.',
    // Notifications Page
    noNewNotifications: 'У вас нет новых уведомлений.',
    // Profile Page
    following: 'Подписки',
    followers: 'Подписчики',
    follow: 'Подписаться',
    message: 'Сообщение',
    posts: 'Публикации',
    replies: 'Ответы',
    likes: 'Лайки',
    noPostsYet: 'Пока нет публикаций.',
    noRepliesYet: 'Пока нет ответов.',
    noLikesYet: 'Пока нет лайков.',
    savedPostsArePrivate: 'Сохраненные публикации являются приватными.',
    youHaventSavedPosts: 'Вы еще не сохранили ни одной публикации.',
    youHaventRepliedYet: "Вы еще не ответили ни на одну публикацию.",
    youHaventLikedYet: "Вам еще не понравилась ни одна публикация.",
    // Toasts & Alerts
    error: 'Ошибка',
    success: 'Успешно',
    couldNotFetchDashboardStats: 'Не удалось получить статистику панели управления.',
    userDeleted: 'Пользователь удален',
    userDeletedDesc: (name: string) => `${name} успешно удален.`,
    couldNotDeleteUser: 'Не удалось удалить пользователя. Проверьте правила Firestore.',
    postUpdated: 'Публикация обновлена',
    postUpdatedDesc: (status: 'banned' | 'active') => `Публикация была ${status === 'banned' ? 'забанена' : 'разбанена'}.`,
    couldNotUpdatePost: 'Не удалось обновить статус публикации.',
    postDeleted: 'Публикация удалена',
    postDeletedDesc: 'Публикация успешно удалена.',
    couldNotDeletePost: 'Не удалось удалить публикацию. Проверьте правила Firestore.',
    couldNotFetchPosts: 'Не удалось получить публикации. Возможно, вам потребуется создать индексы Firestore.',
    unfollowed: 'Вы отписались',
    unfollowedDesc: (name: string) => `Вы больше не подписаны на ${name}.`,
    followed: 'Вы подписались',
    followedDesc: (name: string) => `Теперь вы подписаны на ${name}.`,
    actionCouldNotBeCompleted: 'Не удалось завершить действие.',
    fileTooLarge: 'Файл слишком большой',
    imageTooLargeDesc: 'Изображение должно быть меньше 5 МБ.',
    newAvatarSaved: 'Ваш новый аватар сохранен.',
    newCoverSaved: 'Ваша новая обложка сохранена.',
    uploadFailed: 'Ошибка загрузки',
    couldNotUploadImage: 'Не удалось загрузить ваше изображение.',
    couldNotFetchProfile: 'Не удалось получить пользователя профиля.',
    couldNotFetchUserPosts: 'Не удалось получить публикации пользователя. Возможно, вам потребуется создать индекс в Firestore.',
    couldNotFetchSavedPosts: 'Не удалось получить сохраненные публикации.',
    loggedIn: 'Вход выполнен успешно! Перенаправление...',
    loginFailed: 'Ошибка входа',
    googleLoginFailed: 'Не удалось войти через Google. Пожалуйста, попробуйте еще раз.',
    accountCreated: 'Аккаунт успешно создан!',
    signupFailed: 'Ошибка регистрации',
    passwordLengthError: 'Пароль должен содержать не менее 6 символов.',
    googleSignupFailed: 'Не удалось зарегистрироваться через Google. Пожалуйста, попробуйте еще раз.',
    notAuthenticated: 'Не аутентифицирован',
    mustBeLoggedIn: 'Вы должны войти в систему, чтобы создать публикацию.',
    postError: 'Ошибка публикации',
    couldNotCreatePost: 'Не удалось создать публикацию.',
    invalidFile: 'Недопустимый файл',
    invalidImageFile: 'Пожалуйста, выберите файл изображения (jpg, png, gif, webp).',
    invalidVideoFile: 'Пожалуйста, выберите видеофайл (mp4, webm, ogg).',
    fileTooLarge20MB: 'Файл должен быть меньше 20 МБ.',
    postPublished: 'Ваша публикация была опубликована.',
    uploadError: 'Ошибка загрузки',
    loggedOut: 'Вы вышли из системы',
    loggedOutDesc: 'Вы успешно вышли из системы.',
    logoutError: 'Не удалось выйти из системы.',
    postReported: 'На публикацию пожаловались',
    reportThanks: 'Спасибо за ваш отзыв. Мы рассмотрим эту публикацию.',
    couldNotSubmitReport: 'Не удалось отправить вашу жалобу.',
    mustBeLoggedInToComment: 'Вы должны войти в систему, чтобы оставить комментарий.',
    couldNotAddComment: 'Не удалось добавить комментарий.',
    authError: 'Ошибка аутентификации',
    mustBeLoggedInToLike: 'Вы должны войти в систему, чтобы поставить лайк.',
    couldNotUpdateLike: 'Не удалось обновить лайк.',
    mustBeLoggedInToSave: 'Вы должны войти в систему, чтобы сохранить публикацию.',
    postUnsaved: 'Публикация не сохранена',
    postUnsavedDesc: 'Удалено из ваших сохраненных публикаций.',
    postSaved: 'Публикация сохранена',
    postSavedDesc: 'Добавлено в ваши сохраненные публикации.',
    couldNotSavePost: 'Не удалось сохранить публикацию.',
    unauthorized: 'Неавторизованный',
    unauthorizedDelete: 'Вы можете удалять только свои собственные публикации.',
    // Facebook Video Warnings
    unsupportedFacebookLink: 'Неподдерживаемая ссылка Facebook',
    unsupportedFacebookLinkDesc: 'Этот формат ссылки не поддерживается. Пожалуйста, скопируйте прямую ссылку на видео с главной страницы видео.',
    correctLinkFormats: 'Правильные форматы ссылок:',
    videoPageInstructions: 'Перейдите на страницу видео и скопируйте прямой URL видео.',
    // Admin Panel
    adminDashboard: 'Панель администратора',
    adminWelcome: 'Добро пожаловать в центр управления администратора.',
    totalUsers: 'Всего пользователей',
    totalPosts: 'Всего публикаций',
    reportedPosts: 'Сообщенные публикации',
    bannedPosts: 'Забаненные публикации',
    storageUsage: 'Использование хранилища',
    storageUsageDesc: 'Ежемесячное использование облачного хранилища.',
    storageUsageDetail: (usedGb: string, percentage: string, limitGb: number) => `Ежемесячное использование составляет ${usedGb} ГБ (${percentage}%) из лимита ${limitGb} ГБ.`,
    usedStorage: 'Использовано',
    remainingStorage: 'Осталось',
    quickActions: 'Быстрые действия',
    quickActionsDesc: 'Выполняйте общие административные задачи.',
    sendGlobalNotification: 'Отправить глобальное уведомление',
    recalculateStats: 'Пересчитать все статистики',
    disableSite: 'Временно отключить сайт',
    postManagement: 'Управление публикациями',
    postManagementDesc: 'Просматривайте и управляйте всеми публикациями пользователей. Вы можете банить, разбанивать или удалять публикации.',
    author: 'Автор',
    content: 'Содержание',
    reports: 'Жалобы',
    status: 'Статус',
    created: 'Создано',
    actions: 'Действия',
    unknownUser: 'Неизвестный пользователь',
    mediaPost: 'Медиа-публикация',
    banPost: 'Забанить публикацию',
    unbanPost: 'Разбанить публикацию',
    userManagement: 'Управление пользователями',
    userManagementDesc: 'Просматривайте и управляйте всеми зарегистрированными пользователями.',
    user: 'Пользователь',
    email: 'Электронная почта',
    joined: 'Присоединился',
    deleteUser: 'Удалить пользователя',
};

const pt: typeof en = {
    home: 'Início',
    explore: 'Explorar',
    notifications: 'Notificações',
    profile: 'Perfil',
    createPost: 'Criar Publicação',
    settings: 'Configurações',
    appearance: 'Aparência',
    toggleTheme: 'Alternar tema',
    colorTheme: 'Tema de Cores',
    language: 'Idioma',
    logout: 'Sair',
    whatsOnYourMind: 'No que você está pensando?',
    shareWithCommunity: "Compartilhe seus pensamentos, fotos, vídeos ou links com a comunidade.",
    writePostPlaceholder: "O que está acontecendo? #hashtag",
    selectImageToUpload: 'Selecione uma imagem para enviar',
    selectVideoToUpload: 'Selecione um vídeo para enviar',
    post: 'Publicar',
    posting: 'Publicando...',
    linkUrlPlaceholder: 'Digite o link para compartilhar',
    save: 'Salvar',
    saved: 'Salvo',
    reportPost: 'Denunciar Publicação',
    reportDescription: 'Por favor, forneça um motivo para denunciar esta publicação. Seu feedback é importante para a segurança da comunidade.',
    reportPlaceholder: 'por exemplo, spam, conteúdo impróprio, assédio...',
    cancel: 'Cancelar',
    submitReport: 'Enviar Denúncia',
    deletePost: 'Excluir Publicação',
    createNewPost: 'Criar uma nova publicação',
    welcomeToUmmahConnect: 'Bem-vindo ao UmmahConnect!',
    writeAComment: 'Escreva um comentário...',
    send: 'Enviar',
    // Explore Page
    exploreDescription: 'Descubra o conteúdo mais popular da comunidade.',
    mostLikedPosts: 'Publicações Mais Curtidas',
    mostCommentedPosts: 'Publicações Mais Comentadas',
    noImagePostsToExplore: 'Nenhuma publicação com imagem para explorar ainda.',
    // Notifications Page
    noNewNotifications: 'Você não tem novas notificações.',
    // Profile Page
    following: 'Seguindo',
    followers: 'Seguidores',
    follow: 'Seguir',
    message: 'Mensagem',
    posts: 'Publicações',
    replies: 'Respostas',
    likes: 'Curtidas',
    noPostsYet: 'Nenhuma publicação ainda.',
    noRepliesYet: 'Nenhuma resposta ainda.',
    noLikesYet: 'Nenhuma curtida ainda.',
    savedPostsArePrivate: 'As publicações salvas são privadas.',
    youHaventSavedPosts: 'Você ainda não salvou nenhuma publicação.',
    youHaventRepliedYet: "Você ainda não respondeu a nenhuma publicação.",
    youHaventLikedYet: "Você ainda não curtiu nenhuma publicação.",
    // Toasts & Alerts
    error: 'Erro',
    success: 'Sucesso',
    couldNotFetchDashboardStats: 'Não foi possível buscar as estatísticas do painel.',
    userDeleted: 'Usuário Excluído',
    userDeletedDesc: (name: string) => `${name} foi excluído com sucesso.`,
    couldNotDeleteUser: 'Não foi possível excluir o usuário. Verifique as regras do Firestore.',
    postUpdated: 'Publicação Atualizada',
    postUpdatedDesc: (status: 'banned' | 'active') => `A publicação foi ${status === 'banned' ? 'banida' : 'desbanida'}.`,
    couldNotUpdatePost: 'Não foi possível atualizar o status da publicação.',
    postDeleted: 'Publicação Excluída',
    postDeletedDesc: 'A publicação foi excluída com sucesso.',
    couldNotDeletePost: 'Não foi possível excluir a publicação. Verifique as regras do Firestore.',
    couldNotFetchPosts: 'Não foi possível buscar as publicações. Você pode precisar criar índices do Firestore.',
    unfollowed: 'Deixou de Seguir',
    unfollowedDesc: (name: string) => `Você não está mais seguindo ${name}.`,
    followed: 'Seguindo',
    followedDesc: (name: string) => `Você agora está seguindo ${name}.`,
    actionCouldNotBeCompleted: 'Não foi possível concluir a ação.',
    fileTooLarge: 'Arquivo Muito Grande',
    imageTooLargeDesc: 'A imagem deve ser menor que 5MB.',
    newAvatarSaved: 'Seu novo avatar foi salvo.',
    newCoverSaved: 'Sua nova foto de capa foi salva.',
    uploadFailed: 'Falha no Upload',
    couldNotUploadImage: 'Não foi possível carregar sua imagem.',
    couldNotFetchProfile: 'Não foi possível buscar o usuário do perfil.',
    couldNotFetchUserPosts: 'Não foi possível buscar as publicações do usuário. Você pode precisar criar um índice no Firestore.',
    couldNotFetchSavedPosts: 'Não foi possível buscar as publicações salvas.',
    loggedIn: 'Login efetuado com sucesso! Redirecionando...',
    loginFailed: 'Falha no Login',
    googleLoginFailed: 'Não foi possível iniciar o login com o Google. Por favor, tente novamente.',
    accountCreated: 'Conta criada com sucesso!',
    signupFailed: 'Falha no Cadastro',
    passwordLengthError: 'A senha deve ter pelo menos 6 caracteres.',
    googleSignupFailed: 'Não foi possível iniciar o cadastro com o Google. Por favor, tente novamente.',
    notAuthenticated: 'Não Autenticado',
    mustBeLoggedIn: 'Você precisa estar logado para criar uma publicação.',
    postError: 'Erro na Publicação',
    couldNotCreatePost: 'Não foi possível criar a publicação.',
    invalidFile: 'Arquivo Inválido',
    invalidImageFile: 'Por favor, selecione um arquivo de imagem (jpg, png, gif, webp).',
    invalidVideoFile: 'Por favor, selecione um arquivo de vídeo (mp4, webm, ogg).',
    fileTooLarge20MB: 'O arquivo deve ser menor que 20MB.',
    postPublished: 'Sua publicação foi publicada.',
    uploadError: 'Erro de Upload',
    loggedOut: 'Sessão Encerrada',
    loggedOutDesc: 'Você saiu com sucesso.',
    logoutError: 'Falha ao sair.',
    postReported: 'Publicação Denunciada',
    reportThanks: 'Obrigado pelo seu feedback. Analisaremos esta publicação.',
    couldNotSubmitReport: 'Não foi possível enviar sua denúncia.',
    mustBeLoggedInToComment: 'Você precisa estar logado para comentar.',
    couldNotAddComment: 'Não foi possível adicionar o comentário.',
    authError: 'Erro de Autenticação',
    mustBeLoggedInToLike: 'Você precisa estar logado para curtir uma publicação.',
    couldNotUpdateLike: 'Não foi possível atualizar a curtida.',
    mustBeLoggedInToSave: 'Você precisa estar logado para salvar uma publicação.',
    postUnsaved: 'Publicação Não Salva',
    postUnsavedDesc: 'Removido de suas publicações salvas.',
    postSaved: 'Publicação Salva',
    postSavedDesc: 'Adicionado às suas publicações salvas.',
    couldNotSavePost: 'Não foi possível salvar a publicação.',
    unauthorized: 'Não Autorizado',
    unauthorizedDelete: 'Você só pode excluir suas próprias publicações.',
    // Facebook Video Warnings
    unsupportedFacebookLink: 'Link do Facebook Não Suportado',
    unsupportedFacebookLinkDesc: 'Este formato de link não é suportado. Por favor, copie o link direto do vídeo da página principal do vídeo.',
    correctLinkFormats: 'Formatos de link corretos:',
    videoPageInstructions: 'Vá para a página do vídeo e copie a URL direta do vídeo.',
    // Admin Panel
    adminDashboard: 'Painel do Administrador',
    adminWelcome: 'Bem-vindo ao centro de controle do administrador.',
    totalUsers: 'Total de Usuários',
    totalPosts: 'Total de Publicações',
    reportedPosts: 'Publicações Denunciadas',
    bannedPosts: 'Publicações Banidas',
    storageUsage: 'Uso de Armazenamento',
    storageUsageDesc: 'Uso mensal de armazenamento em nuvem.',
    storageUsageDetail: (usedGb: string, percentage: string, limitGb: number) => `O uso mensal é de ${usedGb} GB (${percentage}%) do limite de ${limitGb} GB.`,
    usedStorage: 'Usado',
    remainingStorage: 'Restante',
    quickActions: 'Ações Rápidas',
    quickActionsDesc: 'Execute tarefas administrativas comuns.',
    sendGlobalNotification: 'Enviar Notificação Global',
    recalculateStats: 'Recalcular Todas as Estatísticas',
    disableSite: 'Desativar Site Temporariamente',
    postManagement: 'Gerenciamento de Publicações',
    postManagementDesc: 'Visualize e gerencie todas as publicações de usuários. Você pode banir, desbanir ou excluir publicações.',
    author: 'Autor',
    content: 'Conteúdo',
    reports: 'Denúncias',
    status: 'Status',
    created: 'Criado',
    actions: 'Ações',
    unknownUser: 'Usuário Desconhecido',
    mediaPost: 'Publicação de Mídia',
    banPost: 'Banir Publicação',
    unbanPost: 'Desbanir Publicação',
    userManagement: 'Gerenciamento de Usuários',
    userManagementDesc: 'Visualize e gerencie todos os usuários registrados.',
    user: 'Usuário',
    email: 'E-mail',
    joined: 'Ingressou em',
    deleteUser: 'Excluir Usuário',
};

const id: typeof en = {
    home: 'Beranda',
    explore: 'Jelajahi',
    notifications: 'Notifikasi',
    profile: 'Profil',
    createPost: 'Buat Postingan',
    settings: 'Pengaturan',
    appearance: 'Tampilan',
    toggleTheme: 'Ganti tema',
    colorTheme: 'Tema Warna',
    language: 'Bahasa',
    logout: 'Keluar',
    whatsOnYourMind: 'Apa yang ada di pikiranmu?',
    shareWithCommunity: "Bagikan pemikiran, foto, video, atau tautan Anda dengan komunitas.",
    writePostPlaceholder: "Apa yang sedang terjadi? #hashtag",
    selectImageToUpload: 'Pilih gambar untuk diunggah',
    selectVideoToUpload: 'Pilih video untuk diunggah',
    post: 'Kirim',
    posting: 'Mengirim...',
    linkUrlPlaceholder: 'Masukkan tautan untuk dibagikan',
    save: 'Simpan',
    saved: 'Disimpan',
    reportPost: 'Laporkan Postingan',
    reportDescription: 'Harap berikan alasan untuk melaporkan postingan ini. Umpan balik Anda penting untuk keamanan komunitas.',
    reportPlaceholder: 'misalnya, spam, konten tidak pantas, pelecehan...',
    cancel: 'Batal',
    submitReport: 'Kirim Laporan',
    deletePost: 'Hapus Postingan',
    createNewPost: 'Buat postingan baru',
    welcomeToUmmahConnect: 'Selamat datang di UmmahConnect!',
    writeAComment: 'Tulis komentar...',
    send: 'Kirim',
    // Explore Page
    exploreDescription: 'Temukan konten paling populer dari komunitas.',
    mostLikedPosts: 'Postingan Paling Disukai',
    mostCommentedPosts: 'Postingan Paling Banyak Dikomentari',
    noImagePostsToExplore: 'Belum ada postingan gambar untuk dijelajahi.',
    // Notifications Page
    noNewNotifications: 'Anda tidak memiliki notifikasi baru.',
    // Profile Page
    following: 'Mengikuti',
    followers: 'Pengikut',
    follow: 'Ikuti',
    message: 'Pesan',
    posts: 'Postingan',
    replies: 'Balasan',
    likes: 'Suka',
    noPostsYet: 'Belum ada postingan.',
    noRepliesYet: 'Belum ada balasan.',
    noLikesYet: 'Belum ada suka.',
    savedPostsArePrivate: 'Postingan yang disimpan bersifat pribadi.',
    youHaventSavedPosts: 'Anda belum menyimpan postingan apa pun.',
    youHaventRepliedYet: "Anda belum membalas postingan apa pun.",
    youHaventLikedYet: "Anda belum menyukai postingan apa pun.",
    // Toasts & Alerts
    error: 'Kesalahan',
    success: 'Berhasil',
    couldNotFetchDashboardStats: 'Tidak dapat mengambil statistik dasbor.',
    userDeleted: 'Pengguna Dihapus',
    userDeletedDesc: (name: string) => `${name} berhasil dihapus.`,
    couldNotDeleteUser: 'Tidak dapat menghapus pengguna. Periksa aturan Firestore.',
    postUpdated: 'Postingan Diperbarui',
    postUpdatedDesc: (status: 'banned' | 'active') => `Postingan telah ${status === 'banned' ? 'diblokir' : 'dibuka blokirnya'}.`,
    couldNotUpdatePost: 'Tidak dapat memperbarui status postingan.',
    postDeleted: 'Postingan Dihapus',
    postDeletedDesc: 'Postingan telah berhasil dihapus.',
    couldNotDeletePost: 'Tidak dapat menghapus postingan. Periksa aturan Firestore.',
    couldNotFetchPosts: 'Tidak dapat mengambil postingan. Anda mungkin perlu membuat indeks Firestore.',
    unfollowed: 'Berhenti Mengikuti',
    unfollowedDesc: (name: string) => `Anda tidak lagi mengikuti ${name}.`,
    followed: 'Mengikuti',
    followedDesc: (name: string) => `Anda sekarang mengikuti ${name}.`,
    actionCouldNotBeCompleted: 'Tidak dapat menyelesaikan tindakan.',
    fileTooLarge: 'File Terlalu Besar',
    imageTooLargeDesc: 'Gambar harus lebih kecil dari 5MB.',
    newAvatarSaved: 'Avatar baru Anda telah disimpan.',
    newCoverSaved: 'Foto sampul baru Anda telah disimpan.',
    uploadFailed: 'Unggahan Gagal',
    couldNotUploadImage: 'Tidak dapat mengunggah gambar Anda.',
    couldNotFetchProfile: 'Tidak dapat mengambil pengguna profil.',
    couldNotFetchUserPosts: 'Tidak dapat mengambil postingan pengguna. Anda mungkin perlu membuat indeks di Firestore.',
    couldNotFetchSavedPosts: 'Tidak dapat mengambil postingan yang disimpan.',
    loggedIn: 'Berhasil masuk! Mengalihkan...',
    loginFailed: 'Gagal Masuk',
    googleLoginFailed: 'Tidak dapat memulai login Google. Silakan coba lagi.',
    accountCreated: 'Akun berhasil dibuat!',
    signupFailed: 'Gagal Mendaftar',
    passwordLengthError: 'Kata sandi harus minimal 6 karakter.',
    googleSignupFailed: 'Tidak dapat memulai pendaftaran Google. Silakan coba lagi.',
    notAuthenticated: 'Tidak Terautentikasi',
    mustBeLoggedIn: 'Anda harus masuk untuk membuat postingan.',
    postError: 'Kesalahan Postingan',
    couldNotCreatePost: 'Tidak dapat membuat postingan.',
    invalidFile: 'File Tidak Valid',
    invalidImageFile: 'Silakan pilih file gambar (jpg, png, gif, webp).',
    invalidVideoFile: 'Silakan pilih file video (mp4, webm, ogg).',
    fileTooLarge20MB: 'File harus lebih kecil dari 20MB.',
    postPublished: 'Postingan Anda telah dipublikasikan.',
    uploadError: 'Kesalahan Unggahan',
    loggedOut: 'Keluar',
    loggedOutDesc: 'Anda telah berhasil keluar.',
    logoutError: 'Gagal keluar.',
    postReported: 'Postingan Dilaporkan',
    reportThanks: 'Terima kasih atas umpan balik Anda. Kami akan meninjau postingan ini.',
    couldNotSubmitReport: 'Tidak dapat mengirimkan laporan Anda.',
    mustBeLoggedInToComment: 'Anda harus masuk untuk berkomentar.',
    couldNotAddComment: 'Tidak dapat menambahkan komentar.',
    authError: 'Kesalahan Otentikasi',
    mustBeLoggedInToLike: 'Anda harus masuk untuk menyukai postingan.',
    couldNotUpdateLike: 'Tidak dapat memperbarui suka.',
    mustBeLoggedInToSave: 'Anda harus masuk untuk menyimpan postingan.',
    postUnsaved: 'Postingan Batal Disimpan',
    postUnsavedDesc: 'Dihapus dari postingan Anda yang disimpan.',
    postSaved: 'Postingan Disimpan',
    postSavedDesc: 'Ditambahkan ke postingan Anda yang disimpan.',
    couldNotSavePost: 'Tidak dapat menyimpan postingan.',
    unauthorized: 'Tidak Sah',
    unauthorizedDelete: 'Anda hanya dapat menghapus postingan Anda sendiri.',
    // Facebook Video Warnings
    unsupportedFacebookLink: 'Tautan Facebook Tidak Didukung',
    unsupportedFacebookLinkDesc: 'Format tautan ini tidak didukung. Silakan salin tautan video langsung dari halaman utama video.',
    correctLinkFormats: 'Format tautan yang benar:',
    videoPageInstructions: 'Buka halaman video dan salin URL video langsung.',
    // Admin Panel
    adminDashboard: 'Dasbor Admin',
    adminWelcome: 'Selamat datang di pusat kendali admin.',
    totalUsers: 'Total Pengguna',
    totalPosts: 'Total Postingan',
    reportedPosts: 'Postingan yang Dilaporkan',
    bannedPosts: 'Postingan yang Diblokir',
    storageUsage: 'Penggunaan Penyimpanan',
    storageUsageDesc: 'Penggunaan penyimpanan cloud bulanan.',
    storageUsageDetail: (usedGb: string, percentage: string, limitGb: number) => `Penggunaan bulanan adalah ${usedGb} GB (${percentage}%) dari batas ${limitGb} GB.`,
    usedStorage: 'Digunakan',
    remainingStorage: 'Tersisa',
    quickActions: 'Tindakan Cepat',
    quickActionsDesc: 'Lakukan tugas administratif umum.',
    sendGlobalNotification: 'Kirim Notifikasi Global',
    recalculateStats: 'Hitung Ulang Semua Statistik',
    disableSite: 'Nonaktifkan Situs Sementara',
    postManagement: 'Manajemen Postingan',
    postManagementDesc: 'Lihat dan kelola semua postingan pengguna. Anda dapat memblokir, membuka blokir, atau menghapus postingan.',
    author: 'Penulis',
    content: 'Konten',
    reports: 'Laporan',
    status: 'Status',
    created: 'Dibuat',
    actions: 'Tindakan',
    unknownUser: 'Pengguna Tidak Dikenal',
    mediaPost: 'Postingan Media',
    banPost: 'Blokir Postingan',
    unbanPost: 'Buka Blokir Postingan',
    userManagement: 'Manajemen Pengguna',
    userManagementDesc: 'Lihat dan kelola semua pengguna terdaftar.',
    user: 'Pengguna',
    email: 'Email',
    joined: 'Bergabung',
    deleteUser: 'Hapus Pengguna',
};


export const appStrings = {
    en,
    tr,
    es,
    fr,
    ar,
    hi,
    bn,
    ru,
    pt,
    id,
};

export type AppStrings = typeof appStrings;